name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      env:
        GS_SECRET_ACCESS_KEY: ${{ secrets.GS_SECRET_ACCESS_KEY }}
        GS_ACCESS_KEY_ID: ${{ secrets.GS_ACCESS_KEY_ID }}
      run: make run_tests_ci

